# Generated by Django 4.1 on 2022-10-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Naaew',
        ),
    ]
