# Generated by Django 4.1 on 2022-10-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0002_delete_naaew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollchoice',
            name='choice_id',
        ),
    ]
