# Generated by Django 4.1 on 2022-10-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0003_remove_pollchoice_choice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollchoice',
            name='number_of_selection',
            field=models.IntegerField(default=1),
        ),
    ]
