# Generated by Django 4.1 on 2022-10-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0004_pollchoice_number_of_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoice',
            name='number_of_selection',
            field=models.IntegerField(default=0),
        ),
    ]
